### ISSUE TITLE
Error when downloading something from yt

### ISSUE THREAD

**Issue by HeIIow2** [HeIIow2/music-downloader#1]
q to quit, ok to download, .. for previous options, . for current options, int for this element: 13 
artists: 1; releases 1; tracks 10
0)	artist:	'Lorna Shore' from US, 'American deathcore band'
1)	release:	'Immortal'
2)	track:	'Darkest Spawn'
3)	track:	'Death Portrait'
4)	track:	'Hollow Sentence'
5)	track:	'Immortal'
6)	track:	'King Ov Deception'
7)	track:	'Misery System'
8)	track:	'Obsession'
9)	track:	'Relentless Torment'
10)	track:	'This Is Hell'
11)	track:	'Warpath of Disease'

q to quit, ok to download, .. for previous options, . for current options, int for this element: ok
INFO:root:Starting Downloading of metadata
INFO:root:Fetching Download Links
[download] Downloading playlist: GBDHC2012001
[youtube:search] query "GBDHC2012001": Downloading page 1
[youtube:search] query "GBDHC2012001": Downloading page 2
[youtube:search] playlist GBDHC2012001: Downloading 0 videos
[download] Finished downloading playlist: GBDHC2012001
Traceback (most recent call last):
  File "/home/lars/Projekts/big projects/music-downloader/src/main.py", line 104, in <module>
    cli(start_at=0)
  File "/home/lars/Projekts/big projects/music-downloader/src/main.py", line 92, in cli
    download_links.Download(file=STEP_TWO_CACHE, metadata_csv=STEP_ONE_CACHE, temp=TEMP, session=session)
  File "/media/lars/Volume/Projekts/big projects/music-downloader/src/download_links.py", line 29, in __init__
    youtube_url = youtube_music.get_youtube_url(row)
  File "/media/lars/Volume/Projekts/big projects/music-downloader/src/youtube_music.py", line 31, in get_youtube_url
    result = get_youtube_from_isrc(row['isrc'])
  File "/media/lars/Volume/Projekts/big projects/music-downloader/src/youtube_music.py", line 17, in get_youtube_from_isrc
    video = ydl.extract_info(f"ytsearch:{isrc}", download=False)['entries'][0]
IndexError: list index out of range

**Comment by HeIIow2** [comment]
youtube downloader just takes the first results... thus throwing an error when there are 0 results
