### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by charizard1596** [HeIIow2/music-downloader#10]
Hello!
After installing the program using pip, I get the following error when running it.
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/music-kraken", line 5, in <module>
    from music_kraken import cli
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music_kraken/__init__.py", line 15, in <module>
    from .lyrics import lyrics
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music_kraken/lyrics/lyrics.py", line 5, in <module>
    from . import genius
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music_kraken/lyrics/genius.py", line 25, in <module>
    class Song:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music_kraken/lyrics/genius.py", line 66, in Song
    def fetch_lyrics(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
I'm on MacOS Big Sur, Python 3.9.4
Would someone mind checking this out?

**Comment by HeIIow2** [comment]
# Hi. First of thanks for using my program,

I know what you're problem is.

I used [Type hinting](https://docs.python.org/3/library/typing.html) here:

```python
def fetch_lyrics(self) -> str | None:
    pass
``` 

with `str | None`  I tell python, me and my IDE that this function returns either a string or None. Ik Ik returning None = bad practice but whatever!  
Thing is, the syntax to hint with `|` for the *or* thingie has been introduced in [python 3.10](https://docs.python.org/3/library/types.html#types.UnionType). But you use python 3.9.4. 

So it should work once you upgrade.  
Please let me know if you run into any more issues!!
Cheers. :purple_heart: :blue_heart: :white_heart:
